### ISSUE TITLE
可以像OpenPrompt项目那样提供一些样例代码吗？

### ISSUE THREAD

**Issue by fade-color** [thunlp/OpenDelta#1]
在使用中有一些不太清楚的地方，希望可以有些详细的代码参考，感谢！

目前遇到的问题：在使用`PrefixModel`时，指定`modified_modules=["0.layer.0"]`和不传入`modified_modules`参数时reparams的参数不一样，是使用的方式不对吗

`modified_modules=["0.layer.0"]`时：`reparams.control_trans.2:  weight:[3072, 512] bias:[3072] `，而且在model.generate时会报错：`The size of tensor a (2) must match the size of tensor b (12) at non-singleton dimension 3`

不传入该参数时：`reparams.control_trans.2:  weight:[36864, 512] bias:[36864] `，可以正常generate

模型使用T5

**Comment by ShengdingHu** [comment]
Yes, you may have some misunderstanding of the usage. We will soon (1~2 days) add a more detailed tutorial about [name_based_addressing](https://opendelta.readthedocs.io/en/latest/notes/keyfeature.html#namebasedaddr).

**Comment by ShengdingHu** [comment]
Ah, I find that your problem is not very related to name-based-addressing. It's because adding Prefix to only a part of layers is still an experimental feature. This feature is not as easy as the other method. Because the attention mask need to be changed across layers, and especially for T5, the relative attention need special care. But we will try to support this feature in Prefix Tuning. You can try other delta methods first.

**Comment by ShengdingHu** [comment]
See docs [here](https://opendelta.readthedocs.io/en/latest/modules/deltas.html#prefix-tuning)
